### ISSUE TITLE
Fetch CSL styles from zotero.org, not citationstyles.org

### ISSUE THREAD

**Issue by mfenner** [ORCID-EU-Labs/orcid-feed#1]

**Comment by rmzelle** [comment]
Are there any issues with getting the styles directly from GitHub?

**Comment by mfenner** [comment]
No, I was only following the advice you give at citationstyles.org (http://citationstyles.org/faq/). I have also implemented support for dependent styles (which of course would work with either repo).

**Comment by rmzelle** [comment]
I wrote that mainly with regular users in mind. The Zotero Style Repository is easier to navigate than the GitHub one. Developers should probably just pull their styles from GitHub. But it shouldn't really matter (one benefit of the Zotero repository is that it updates the `<updated/>` time stamp of the styles with their modification date).

**Comment by mfenner** [comment]
OK. I probably leave it linked to zotero.org for now.
